version: "3"

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=seguro123
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - PORT=5678
